enactjs/eslint-config-enact

index.js
package.json
strict.js

Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com

Update to react plugin 7.9.1

---

index.js

Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

Support process global for process.env namespace substitution support.

---

index.js

Remove Mocha environment, add Jest global environment.
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

PLAT-68130: Support Jest globals and remove unneeded Mocha globals

---

index.js
strict.js

See also
https://eslint.org/docs/rules/camelcase#allow
Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>

PLAT-53066: Update camelcase rule for `^UNSAFE_` react lifecycle methods

---

strict.js

Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com

PLAT-86396: Ignore indent in template literals

---

index.js

Enact-DCO-1.0-Signed-off-by: Roy Sutton roy.sutton@lge.com

Add support for parsing ES2018

---

index.js

This PR changes the rules related new JSX transform.
Enact-DCO-1.0-Signed-off-by: Mikyung Kim (mikyung27.kim@lge.com)

PLAT-121645: Changed rule for importing React for JSX

---

CHANGELOG.md
index.js
package-lock.json
package.json

This PR merges `feature/react17` branch to `develop`.
Enact-DCO-1.0-Signed-off-by: Mikyung Kim (mikyung27.kim@lge.com)

Merge feature/react17 to develop

---

CHANGELOG.md
index.js

This PR fixes wrong glob patterns for the test files.
Enact-DCO-1.0-Signed-off-by: Mikyung Kim (mikyung27.kim@lge.com)

PLAT-138171: Fixed the glob patterns for test files

---

CHANGELOG.md
index.js
package.json

Add @testing-library/react related lint rules in Enact CLI
* Add `eslint-plugin-testing-library` module
* Add @testing-library/react related lint rules in Enact CLI
(https://github.com/facebook/create-react-app/blob/main/packages/eslint-config-react-app/jest.js)
WRN-2491
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

WRN-2491: Add @testing-library/react related lint rules

---

npm-shrinkwrap.json
package.json

In this PR, updated react version to 18 and related packages.

WRN-20224: [React18] Update react dependencies

---

.travis.yml
CHANGELOG.md
README.md
docs/index.md
index.js
npm-shrinkwrap.json
package.json

Merge feature/webpack5 branch to develop
Enact-DCO-1.0-Signed-off-by: Mikyung Kim ([mikyung27.kim@lge.com](mailto:mikyung27.kim@lge.com))

WRO-231: Merge feature/webpack5 to develop

---

npm-shrinkwrap.json
package.json

Updated package dependencies to latest versions

WRP-3068: Update package dependencies to fix security vulnerabilities

---

index.js
npm-shrinkwrap.json
package.json

Previously, there were attempts to install each eslint-related module in one repo(ex: eslint-config-enact) so that each tooling (dev-utils, cli, storybook-utils, ui-test-utils) does not install additional eslint-related modules.
The installation of eslint-config-enact alone did not install the necessary eslint-related modules, so it had to be managed separately, and the reason was not known.
This patch is a solution for a longstanding https://github.com/eslint/eslint/issues/3458 that would allow a shared ESLint config to bring along its own plugins, rather than imposing peer dependencies on every consumer of the config.
Doing so greatly reduces the copy+pasting and version management for all the other projects …

WRP-6904: Fix eslint shareable config using rushstack/eslint-patch

---

npm-shrinkwrap.json
package.json

Updated dependencies version to fix vulnerabilities
All dependencies now use the latest minor version.
There were no breaking changes affecting this repo.
WRP-17865
https://github.com/babel/babel/releases
https://github.com/eslint/eslint/releases
https://github.com/testing-library/eslint-plugin-testing-library/releases
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

WRP-17865: Update dependencies to fix vulnerabilities

---

CHANGELOG.md
index.js
strict.js

Reverts enactjs/eslint-config-enact#68

Revert "WRP-6905: Support web-worker global variables"

---

npm-shrinkwrap.json
package.json

Updated dependencies version to fix vulnerabilities
All dependencies now use the latest minor version.
There were no breaking changes affecting this repo.
WRP-28228
https://github.com/eslint/eslint/releases
https://github.com/jest-community/eslint-plugin-jest/releases
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

WRP-28228: Update minor dependencies to fix vulnerabilities

---

npm-shrinkwrap.json
package.json

Update package dependencies to fix security vulnerabilities
There were NO breaking changes affecting this repo.
WRQ-3494
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

WRQ-3494: Update package dependencies to fix security vulnerabilities

---

CHANGELOG.md
index.js
npm-shrinkwrap.json
package.json

From the PRs below, we removed duplicated eslint-related modules on tooling repos in `feature/unify-eslint-modules` branch.
PRs:
https://github.com/enactjs/eslint-config-enact/pull/66 (feature/unify-eslint-modules)
https://github.com/enactjs/dev-utils/pull/123 (feature/unify-eslint-modules)
https://github.com/enactjs/cli/pull/326 (feature/unify-eslint-modules)
https://github.com/enactjs/storybook-utils/pull/54 (feature/unify-eslint-modules)
https://github.com/enactjs/ui-test-utils/pull/137 (feature/unify-eslint-modules)
Enact team decided not to merge those changes into 'develop' at that time, but to merge them now.
[//]: # (What is the impact of this change and *why* was …

WRQ-240: Merge `feature/unify-eslint-modules` branch to `develop` branch

---

CHANGELOG.md
index.js
strict.js

Reverts enactjs/eslint-config-enact#78

Revert "WRQ-214: Support web-worker global variables"

---

npm-shrinkwrap.json
package.json

Update react related modules to v19
Update react related modules to v19
WRQ-21653
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

WRQ-21653: Update react related modules to v19

---

npm-shrinkwrap.json
package.json

Updated dependencies to the latest minor version.
Updated dependencies to the latest minor version.
WRQ-25865
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

WRQ-25865: Updated package dependencies to fix security vulnerabilities

---

CHANGELOG.md
index.js

In WRQ-15997, an deprecated rule has been found.
Fix a rule: no-new-object(deprecated) -> no-object-constructor
WRQ-15997
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

WRQ-15997: Fix a rule: no-new-object(deprecated) -> no-object-constructor

---

npm-shrinkwrap.json
package.json

Updated package dependencies to fix security vulnerabilities
Updated package dependencies to fix security vulnerabilities
Major versions will be updated in another ticket:
@stylistic/eslint-plugin-js        ^1.8.1  →  ^2.7.2
@typescript-eslint/eslint-plugin  ^7.18.0  →  ^8.4.0
@typescript-eslint/parser         ^7.18.0  →  ^8.4.0
eslint                            ^8.57.0  →  ^9.9.1
WRR-1116
Enact-DCO-1.0-Signed-off-by: Paul …

WRR-1116: Updated package dependencies to fix security vulnerabilities

---

npm-shrinkwrap.json
package.json

Updated dependencies minor versions
Updated dependencies minor versions
WRR-10055
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com

WRR-10055: Updated package dependencies to fix security vulnerabilities

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Update React19 related dependencies
Update React19 related dependencies
WRR-15936
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)

WRR-15936: Update React19 related dependencies

---

index.js

There're some errors in #92
- `__dirname already defined` error occurred
- Because a new `globals.node` prop added in `languageOptions`, that never used in the past.
- `shared-node-browser` not worked so 62 lint errors occurred
- Because it defined the old(eslint v8 style) way so does not worked.
Reference: https://github.com/sindresorhus/globals/blob/main/globals.json
- Removed `globals.node` in `languageOptions` because it was not used before.
- Fixed `shared-node-browser` because it's not works.
[//]: # (Were any …

WRR-1005: Updated Eslint to version 9 v2
